[package]
name = "glaze"
version = "0.1.0-alpha.1"
authors = ["GiraffeKey <giraffekey@tutanota.com>"]
license = "BSD-3"
edition = "2018"

[lib]
name = "glaze"

[dependencies]
fnv = "1.0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
